use_frameworks!

target 'RandomUser_Example' do
  pod 'RandomUser', :path => '../'
  pod 'Haneke'
  pod 'MBProgressHUD'

  target 'RandomUser_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
